language: php
dist: trusty
php:
  - 5.6
  - 7.0
  - hhvm
install:
  - composer install
script: vendor/bin/phpunit --verbose --coverage-text --coverage-clover=/tmp/sphring/coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover /tmp/sphring/coverage.clover
