language: php
php:
  - 5.5
  - 5.6
  - hhvm
install:
  - composer install
script: phpunit --bootstrap tests/bootstraptravis.php --no-configuration tests --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
